/* XPM */
static char *space_ship[] = {
/* width height ncolors chars_per_pixel */
"32 32 11 1",
/* colors */
"` c black",
"a c cyan",
"b c dodger blue",
"c c grey",
"d c firebrick",
"e c red",
"f c white",
"g c sienna",
"h c slate grey",
"i c yellow",
"j c blue",
/* pixels */
"ffffffffffffffffffffffffffffffff",
"f``````````````````````````````f",
"f``````````````````````````````f",
"f`````````````````````h````h```f",
"f````````````````````hfh```````f",
"f``````````h``````````h````````f",
"f``h```````````````````````````f",
"f``````````````````````````````f",
"f``````````````````````````````f",
"f``````````````fc``````````````f",
"f`````ff``````hcc``````````````f",
"f```hhhaf````hccc``````````````f",
"f````````fh`hcccc``````````````f",
"f````c`````hhhccc``````````````f",
"f`````cc``````hhc``````````````f",
"f```````c```````hhhhhhhhh``````f",
"f`````hc`c````````````cc```````f",
"f````hc`c`c`````````cc``````h``f",
"f```hc`c`c`c```````c```````````f",
"f``hc`c`c`c`c`````c````````````f",
"f``c`c`c`c`c`c```c`````````````f",
"f`````````````c``cd````````````f",
"f``````````````cciee```````````f",
"fb`````````````deeiee``````````f",
"fjb`````````````eeiiee`````````f",
"fajb`````````````eeiie`````````f",
"faajb```````h`````eeiii````````f",
"faaajb``````````````eeie```````f",
"faaaajb```````````````eie``````f",
"fagaaajb``````````````eeii`````f",
"faagaaajb```````````````eee````f",
"ffffffffffffffffffffffffffffffff"
};
